spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      schema-locations: classpath:schema.sql
      mode: always
